name1=input("Enter your 1st friend's name: ")
age1=input("Enter your 1st friend's age: ")
date_of_born1=input("Enter your 1st friend's date of born: ")
name2=input("Enter your 2nd friend's name: ")
age2=input("Enter your 2nd friend's age: ")
date_of_born2=input("Enter your 2nd friend's date of born: ")
name3=input("Enter your 3th friend's name: ")
age3=input("Enter your 3th friend's age:")
date_of_born3=input("Enter your 3th friend's date of born")
name4=input("Enter your 4th friend's name: ")
age4=input("Enter your 4th friend's age:")
date_of_born4=input("Enter your 4th friend's date of born:")
name5=input("Enter your 5th friend's name: ")
age5=input("Enter your 5th friend's age: ")
date_of_born5=input("Enter your 5th friend's date of born:")

print(f"Your 1st friend's name is {name1} and his date of born is {date_of_born1}")
print(f"Your 2nd friend's name is {name2} and his date of born is {date_of_born2}")
print(f"Your 3th friend's name is {name3} and his date of born is {date_of_born3}")
print(f"Your 4th friend's name is {name4} and his date of born is {date_of_born4}")
print(f"Your 5th friend's name is {name5} and his date of born is {date_of_born5}")